#include "printMessage.h"
#include "Character.h"
#include "GenerateRandomNumber.h"
#include <iostream>
#include <string>
#include <windows.h>
#include <conio.h>

using namespace std;

void PrintMessage::gotoXY(int x, int y) 
{
    COORD Pos;
    Pos.X = x;
    Pos.Y = y;
    SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), Pos);
}

int PrintMessage::getcursorlocationY() {
    CONSOLE_SCREEN_BUFFER_INFO csbi;
    GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi);
    int cursorY = csbi.dwCursorPosition.Y;
    return cursorY;
}


void PrintMessage::textColor(unsigned short color)	// 컬러 텍스트 함수 0(검은색)~15(밝은 하얀색)까지 입력
{
	HANDLE hCon = GetStdHandle(STD_OUTPUT_HANDLE);
	SetConsoleTextAttribute(hCon, color);
}

void PrintMessage::printOpening()
{
    // 구현예정
}

void PrintMessage::askName()
{
    system("cls");
    textColor(6);
    gotoXY(43, 6);
    cout << "   ______________________________" << endl;
    gotoXY(43, 7);
    cout << " / \\                             \\." << endl;
    gotoXY(43, 8);
    cout << "|   |                            |." << endl;
    gotoXY(43, 9);
    cout << " \\_/|                            |." << endl;
    gotoXY(43, 10);
    cout << "    |     ";
    textColor(7);    
    cout << "환영합니다.";
    textColor(6);
    cout << "            |." << endl;
    gotoXY(43, 11);
    cout << "    |     ";
    textColor(7);
    cout << "모험가님.";
    textColor(6); 
    cout << "              |." << endl;
    gotoXY(43, 12);
    cout << "    |                            |." << endl;
    gotoXY(43, 13);
    cout << "    |     "; 
    textColor(7); 
    cout << "모험가님의 이름은";
    textColor(6);    
    cout << "      |." << endl;
    gotoXY(43, 14);
    cout << "    |     ";
    textColor(7); 
    cout << "무엇입니까?";
    textColor(6);    
    cout << "            |." << endl;
    
    gotoXY(43, 15);
    cout << "    |                            |." << endl;
    gotoXY(43, 16);
    cout << "    |     ";
    textColor(15);    
    cout << "__________________"; 
    textColor(6);
    cout << "     |." << endl;
    gotoXY(43, 17);
    cout << "    |                            |." << endl;
    gotoXY(43, 18);
    cout << "    |                            |." << endl;
    gotoXY(43, 19);
    cout << "    |                            |." << endl;
    gotoXY(43, 20);
    cout << "    |                            |." << endl;
    gotoXY(43, 21);
    cout << "    |                            |." << endl;
    gotoXY(43, 22);
    cout << "    |   _________________________|__" << endl;
    gotoXY(43, 23);
    cout << "    |  /                           /." << endl;
    gotoXY(43, 24);
    cout << "    \\_/___________________________/." << endl;
    textColor(7);
    gotoXY(53,16); // 이름 입력칸 좌표 (53, 16) 로 커서 갖다놓기
}
void PrintMessage::afterName(string name)
{
    Character* player = Character::getInstance(name);

    for (int i = 10; i <= 16; i++)
    {
        gotoXY(53, i);
        cout << "                       ";
        Sleep(100);
    }
    
    gotoXY(53, 10);
    textColor(7);
    cout << "반갑습니다.";
    gotoXY(53, 11);
    cout << player->getName() << ".";
    Sleep(1500);
    gotoXY(53, 13);
    cout << "당신의 능력치입니다.";
    Sleep(1000);
    gotoXY(53, 15);
    cout << "레벨: ";
    gotoXY(61, 15);
    cout << player->getLevel();
    Sleep(800);
    gotoXY(53, 16);
    cout << "체력: 200/200";
    Sleep(800);
    gotoXY(53, 17);
    cout << "골드: ";
    gotoXY(61, 17);
    cout << player->getGold();
    Sleep(800);
    gotoXY(53, 18);
    cout << "대미지: ";
    gotoXY(63, 18);
    cout << player->getAttack();
    Sleep(800);
    gotoXY(53, 19);
    cout << "경험치: 0/100";
    Sleep(800);
    gotoXY(55, 21);
    cout << "행운을 빕니다!";
    Sleep(2000);
    system("cls");
}
void PrintMessage::printIntro()
{   
    gotoXY(2, 8);
	textColor(12);
	cout << "_________";
	textColor(7);
	cout << " ______     __    ______     ";
	textColor(9);
	cout << "_______  ______            _______  _       _________          _______  _______ " << endl;
    gotoXY(2, 9);
	textColor(12);
	cout << "\\__   __/";
	textColor(7);
	cout << "(  __  \\   /__\\  (  __  \\   ";
	textColor(9);
	cout << "(  ___  )(  __  \\ |\\     /|(  ____ \\( (    /|\\__   __/|\\     /|(  ____ )(  ____ \\" << endl;
    gotoXY(2, 10);
	textColor(12);
	cout << "   ) (   ";
	textColor(7);
	cout << "| (  \\  ) ( \\/ ) | (  \\  )  ";
	textColor(9);
	cout << "| (   ) || (  \\  )| )   ( || (    \\/|  \\  ( |   ) (   | )   ( || (    )|| (    \\/" << endl;
    gotoXY(2, 11);
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| |   ) |  \\  /  | |   ) |  ";
	textColor(9);
	cout << "| (___) || |   ) || |   | || (__    |   \\ | |   | |   | |   | || (____)|| (__    " << endl;
    gotoXY(2, 12);
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| |   | |  /  \\/\\| |   | |  ";
	textColor(9);
	cout << "|  ___  || |   | |( (   ) )|  __)   | (\\ \\) |   | |   | |   | ||     __)|  __)   " << endl;
    gotoXY(2, 13);
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| |   ) | / /\\  /| |   ) |  ";
	textColor(9);
	cout << "| (   ) || |   ) | \\ \\_/ / | (      | | \\   |   | |   | |   | || (\\ (   | (      " << endl;
    gotoXY(2, 14);
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| (__/  )(  \\/  \\| (__/  )  ";
	textColor(9);
	cout << "| )   ( || (__/  )  \\   /  | (____/\\| )  \\  |   | |   | (___) || ) \\ \\__| (____/\\" << endl;
    gotoXY(2, 15);
	textColor(12);
	cout << "   )_(   ";
	textColor(7);
	cout << "(______/  \\___/\\/(______/   ";
	textColor(9);
	cout << "|/     \\|(______/    \\_/   (_______/|/    )_)   )_(   (_______)|/   \\__/(_______/" << endl;
	textColor(5);
    Sleep(3000);
    gotoXY(90, 17);
    cout << "by 이것좀 해조" << endl;
	Sleep(1500);
    gotoXY(48, 20);
    textColor(15);
    cout << "캐릭터 작성을 시작합니다."; 
    gotoXY(53, 21);
    cout << "(Press any key)";
    _getch();
}

void PrintMessage::printUpperFrame()
{
    textColor(6);
    cout << "            .-------------------------------------------------------------------------------------------------." << endl;
    cout << "           /  .-.                                                                                         .-.  \\" << endl;
    cout << "          |  /   \\                                                                                       /   \\  |" << endl;
    cout << "          | |\\_.  |                                                                                     |    /| |" << endl;
    cout << "          |\\|  | /|                                                                                     |\\  | |/|" << endl;
    cout << "          | `---' |                                                                                     | `---' |" << endl;
    //cout << "          |       |                                                                                     |       |" << endl;
    //cout << "          |       |                                                                                     |       |" << endl;
    //cout << "          |       |                                                                                     |       |" << endl;
    //cout << "          |       |                                                                                     |       |" << endl;
    //cout << "          |       |-------------------------------------------------------------------------------------|       |" << endl;
    //cout << "          \\       |                                                                                     |       /" << endl;
    //cout << "           \\     /                                                                                       \\     /" << endl;
    //cout << "            `---'                                                                                         `---'" << endl;
    
    textColor(15);
    gotoXY(30, 1);
    cout << "   _     ___  _";
    gotoXY(47, 1);
    cout << "    _  ____  _     ____  _      ____  _    ";
    gotoXY(30, 2);
    cout << "  / \\__/|\\  \\//";
    gotoXY(47, 2);
    cout << "   / |/  _ \\/ \\ /\\/  __\\/ \\  /|/  _ \\/ \\   ";
    gotoXY(30, 3);
    cout << "  | |\\/|| \\  / ";
    gotoXY(47, 3);
    cout << "   | || / \\|| | |||  \\/|| |\\ ||| / \\|| |   ";
    gotoXY(30, 4);
    cout << "  | |  || / /  ";
    gotoXY(47, 4);
    cout << "/\\_| || \\_/|| \\_/||    /| | \\||| |-||| |_/\\";
    gotoXY(30, 5);
    cout << "  \\_/  \\|/_/   ";
    gotoXY(47, 5);
    cout << "\\____/\\____/\\____/\\_/\\_\\\\_/  \\|\\_/ \\|\\____/";
    textColor(7);
    gotoXY(0, 6);
}
void PrintMessage::printLowerFrame()
{
    textColor(6);
    //cout << "            .-------------------------------------------------------------------------------------------------." << endl;
    //cout << "           /  .-.                                                                                         .-.  \\" << endl;
    //cout << "          |  /   \\                                                                                       /   \\  |" << endl;
    //cout << "          | |\\_.  |                                                                                     |    /| |" << endl;
    //cout << "          |\\|  | /|                                                                                     |\\  | |/|" << endl;
    //cout << "          | `---' |                                                                                     | `---' |" << endl;
    //cout << "          |       |                                                                                     |       |" << endl;
    //cout << "          |       |                                                                                     |       |" << endl;
    //cout << "          |       |                                                                                     |       |" << endl;
    cout << "          |       |                                                                                     |       |" << endl;
    cout << "          |       |-------------------------------------------------------------------------------------|       |" << endl;
    cout << "          \\       |                                                                                     |       /" << endl;
    cout << "           \\     /                                                                                       \\     /" << endl;
    cout << "            `---'                                                                                         `---'" << endl;
    textColor(7);
}
void PrintMessage::printFrame()
{
    int randomframe = generateRandomNumber(0, 3);

    switch (randomframe)
    {
    case 0:
        textColor(6);
        cout << "          |       |                                                                                     |       |";
        textColor(7);
        gotoXY(26, getcursorlocationY());
        break;
    case 1:
        textColor(6);
        cout << "          >       |                                                                                     <       |";
        textColor(7);
        gotoXY(26, getcursorlocationY());
        break;
    case 2:
        textColor(6);
        cout << "          |       S                                                                                     |       |";
        textColor(7);
        gotoXY(26, getcursorlocationY());
        break;
    case 3:
        textColor(6);
        cout << "          >       |                                                                                     |       <";
        textColor(7);
        gotoXY(26, getcursorlocationY());
        break;
    }
}

void PrintMessage::printShopRoof()
{
	printFrame();
	cout << endl;
	printFrame();
	cout << "////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\" << endl;
}

void PrintMessage::bossAppears() 
{
    textColor(0);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(1000);
    system("cls");
    textColor(8);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(800);
    system("cls");
    textColor(7);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(800);
    system("cls");
    textColor(12);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(800);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(800);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(0);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(4);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(0);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(4);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(3000);
}

void PrintMessage::displayEpitaph(string name)
{
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                   _____  _____" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  <     `/     |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                   >          (" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |   _     _  |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |  |_) | |_) |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |  | \\ | |   |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |            |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "   ______.______%_|            |__________  _____" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << " _/                                       \\|     |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "|               "; 
	textColor(15);
	cout << "      " << name;
	textColor(7);
	cout << "              <" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "|_____.-._________              ____/|___________|" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  | * fi/ll/in |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  | + 17/01/25 |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |            |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |            |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |   _        <" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                  |__/         |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    cout << "                   / `--.      |" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
    textColor(2);
	cout << "                 %";
	textColor(7);
	cout << "|            |"; 
	textColor(2);
	cout << "%" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
	cout << "             |/.%%";
	textColor(7);
	cout << "|          -< "; 
	textColor(2); 
	cout << "@%%%" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
	cout << "             `\\%`@";
	textColor(7);
	cout << "|     v      |";
	textColor(2); 
	cout << "@@%@%%    " << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
	cout << "           .%%%@@@";
	textColor(7); 
	cout << "|%    |    "; 
	textColor(2); 
	cout << "% @@@%%@%%%%" << endl;
    cout << "          |       |                                                                                     |       |";
    gotoXY(26, getcursorlocationY());
	cout << "      _.%%%%%%@@@@@@%%_/%\\_%@@%%@@@@@@@%%%%%%" << endl;
	textColor(7);
}

void PrintMessage::printCongratulations()
{
	textColor(15);
	
	cout << "  .-------------------------------------------------------------------." << endl;
	cout << " /  .-.            축하합니다!                                     .-. \\" << endl;
	cout << "|  /   \\       고대의 악마를 무찔렀습니다.                       /    \\ |" << endl;
	cout << "| |\\_.  |    먼 옛날 봉인되었던 악마는 봉인 속에서              |    /| |" << endl;
	cout << "|\\|  | /|    물질계를 파멸시킬 사악한 음모를 꾸미고 있었습니다  |\\  | |/|" << endl;
	cout << "| `---' |                                                       | `---' |" << endl;
	cout << "|       |   그러나 당신의 영웅적인 활약으로                     |       |" << endl;
	cout << "|       |   악마의 사악한 계획은 무너지고 물질계의 평화가       |       |" << endl;
	cout << "|       |   다시 한 번 지켜졌습니다.                            |       |" << endl;
	cout << "|       |   이에 우리는 당신에게 무한한 감사와 축복을 전합니다  |       |" << endl;
	cout << "|       |-------------------------------------------------------|       |" << endl;
	cout << "\\       |                                                       |       /" << endl;
	cout << " \\     /                                                         \\     /" << endl;
	cout << "  `---'                                                           `---'" << endl;
	
	textColor(7);
	Sleep(3000);
}