#include "printMessage.h"
#include <iostream>
#include <string>
#include <windows.h>

using namespace std;

void PrintMessage::textColor(unsigned short color)	// 컬러 텍스트 함수 0(검은색)~15(밝은 하얀색)까지 입력
{
	HANDLE hCon = GetStdHandle(STD_OUTPUT_HANDLE);
	SetConsoleTextAttribute(hCon, color);
}

void PrintMessage::printIntro()
{
    system("cls");
	textColor(12);
	cout << "_________";
	textColor(7);
	cout << " ______     __    ______     ";
	textColor(9);
	cout << "_______  ______            _______  _       _________          _______  _______ " << endl;
	textColor(12);
	cout << "\\__   __/";
	textColor(7);
	cout << "(  __  \\   /__\\  (  __  \\   ";
	textColor(9);
	cout << "(  ___  )(  __  \\ |\\     /|(  ____ \\( (    /|\\__   __/|\\     /|(  ____ )(  ____ \\" << endl;
	textColor(12);
	cout << "   ) (   ";
	textColor(7);
	cout << "| (  \\  ) ( \\/ ) | (  \\  )  ";
	textColor(9);
	cout << "| (   ) || (  \\  )| )   ( || (    \\/|  \\  ( |   ) (   | )   ( || (    )|| (    \\/" << endl;
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| |   ) |  \\  /  | |   ) |  ";
	textColor(9);
	cout << "| (___) || |   ) || |   | || (__    |   \\ | |   | |   | |   | || (____)|| (__    " << endl;
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| |   | |  /  \\/\\| |   | |  ";
	textColor(9);
	cout << "|  ___  || |   | |( (   ) )|  __)   | (\\ \\) |   | |   | |   | ||     __)|  __)   " << endl;
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| |   ) | / /\\  /| |   ) |  ";
	textColor(9);
	cout << "| (   ) || |   ) | \\ \\_/ / | (      | | \\   |   | |   | |   | || (\\ (   | (      " << endl;
	textColor(12);
	cout << "   | |   ";
	textColor(7);
	cout << "| (__/  )(  \\/  \\| (__/  )  ";
	textColor(9);
	cout << "| )   ( || (__/  )  \\   /  | (____/\\| )  \\  |   | |   | (___) || ) \\ \\__| (____/\\" << endl;
	textColor(12);
	cout << "   )_(   ";
	textColor(7);
	cout << "(______/  \\___/\\/(______/   ";
	textColor(9);
	cout << "|/     \\|(______/    \\_/   (_______/|/    )_)   )_(   (_______)|/   \\__/(_______/" << endl;
	textColor(7);
	Sleep(3000);
}

void PrintMessage::bossAppears() 
{
    textColor(0);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(1000);
    system("cls");
    textColor(8);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(800);
    system("cls");
    textColor(7);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(800);
    system("cls");
    textColor(12);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    Sleep(800);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(800);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(0);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(4);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(0);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(8);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(400);
    system("cls");
    textColor(4);
    cout << "           .                                                      ." << endl;
    cout << "         .n                   .                 .                  n." << endl;
    cout << "   .   .dP                  dP                   9b                 9b.    ." << endl;
    cout << "  4    qXb         .       dX                     Xb       .        dXp     t" << endl;
    cout << " dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb" << endl;
    cout << " 9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP" << endl;
    cout << "  9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP" << endl;
    cout << "   `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'" << endl;
    cout << "     `9XXXXXXXXXXXP' `9XX'   ..     `98v8P'    ..    `XXP' `9XXXXXXXXXXXP'" << endl;
    cout << "         ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~" << endl;
    cout << "                         )b.  .dbo.dP'`v'`9b.odb.  .dX(" << endl;
    cout << "                       ,dXXXXXXXXXXXb     dXXXXXXXXXXXb." << endl;
    cout << "                      dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb" << endl;
    cout << "                     dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb" << endl;
    cout << "                     9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP" << endl;
    cout << "                      `'      9XXXXXX(   )XXXXXXP      `'" << endl;
    cout << "                               XXXX X.`v'.X XXXX" << endl;
    cout << "                               XP^X'`b   d'`X^XX" << endl;
    cout << "                               X. 9  `   '  P )X" << endl;
    cout << "                               `b  `       '  d'" << endl;
    cout << "                                `             '" << endl;
    textColor(4);
    cout << "                     _   _         _   _         _   _" << endl;
    cout << "                    | | | | __ _  | | | | __ _  | | | | __ _" << endl;
    cout << "                    | |_| |/ _` | | |_| |/ _` | | |_| |/ _` |" << endl;
    cout << "                    |  _  | (_| | |  _  | (_| | |  _  | (_| |" << endl;
    cout << "                    |_| |_|\\__,_| |_| |_|\\__,_| |_| |_|\\__,_|" << endl;
    Sleep(3000);
}

void PrintMessage::displayEpitaph(string name)
{
cout << "                   _____  _____" << endl;
cout << "                  <     `/     |" << endl;
cout << "                   >          (" << endl;
cout << "                  |   _     _  |" << endl;
cout << "                  |  |_) | |_) |" << endl;
cout << "                  |  | \\ | |   |" << endl;
cout << "                  |            |" << endl;
cout << "   ______.______%_|            |__________  _____" << endl;
cout << " _/                                       \\|     |" << endl;
cout << "|               "; 
textColor(15);
cout << "      " << name;
textColor(7);
cout << "              <" << endl;
cout << "|_____.-._________              ____/|___________|" << endl;
cout << "                  | * fi/ll/in |" << endl;
cout << "                  | + 17/01/25 |" << endl;
cout << "                  |            |" << endl;
cout << "                  |            |" << endl;
cout << "                  |   _        <" << endl;
cout << "                  |__/         |" << endl;
cout << "                   / `--.      |" << endl;
textColor(2);
cout << "                 %";
textColor(7);
cout << "|            |"; 
textColor(2);
cout << "%" << endl;
cout << "             |/.%%";
textColor(7);
cout << "|          -< "; 
textColor(2); 
cout << "@%%%" << endl;
cout << "             `\\%`@";
textColor(7);
cout << "|     v      |";
textColor(2); 
cout << "@@%@%%    " << endl;
cout << "           .%%%@@@";
textColor(7); 
cout << "|%    |    "; 
textColor(2); 
cout << "% @@@%%@%%%%" << endl;
cout << "      _.%%%%%%@@@@@@%%_/%\\_%@@%%@@@@@@@%%%%%%" << endl;
textColor(7);
}